app: jack-mexico
frameworkVersion: '3'

service: serverless-nodejs-app

plugins:
  - serverless-dotenv-plugin

useDotenv: true

provider:
  name: aws
  runtime: nodejs14.x
  stage: prod
  region: us-west-1
  environment:
    NODE_VERSION: 14
    NODE_ENV: production
    MONGO_URI: ${env:MONGO_URI}
    API_KEY: ${env:API_KEY}

package:
 patterns:
   - '!.env.example'
   - '!package.json'

	
custom:
  dotenv:
  # add only whats required
    include:
      - MONGO_URI
      - API_KEY

functions:
  app:
    handler: server.server 
    events: # events trigger lambda functions
      - http: # this is an API Gateway HTTP event trigger
          path: /
          method: ANY
          cors: true
      - http: # all routes get proxied to the Express router
          path: /{proxy+}
          method: ANY
          cors: 
            origins: ["capacitor://localhost", "http://localhost", "http://localhost:8080"] # mobile config
            allowCredentials: false
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
              - Access-Control-Allow-Headers
