name: Deploy

on:
  push:
    branches:
      - master

env:
  AWS_DEFAULT_REGION: us-west-1

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Create env file
      run: |
        cat > .env << EOF
        MONGO_URI=${{ secrets.MONGO_URI }}
        API_KEY=${{ secrets.API_KEY }}
        EOF
    - name: Install Serverless Framework
      run: npm install -g serverless
    - name: Serverless AWS authentication
      run: sls config credentials --provider aws --key ${{ secrets.AWS_ACCESS_KEY_ID }} --secret ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    - name: Install NPM dependencies
      run: npm ci
    - name: Deploy Lambda functions
      run: sls deploy
